from __future__ import annotations

from collections.abc import Awaitable
from typing import (
    Any,
    AsyncContextManager,
    ContextManager,
    overload,
    Protocol,
    Sequence,
)

__version__: str
__doc__: str

class ModelVaultFormatError(ValueError): ...
class ModelVaultSchemaError(ValueError): ...
class ModelVaultValidationError(ValueError): ...
class ModelVaultQueryError(ValueError): ...
class ModelVaultTransactionError(RuntimeError): ...

class AsyncTransaction(AsyncContextManager[None]):
    async def __aenter__(self) -> None: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None = ...,
        exc_value: BaseException | None = ...,
        traceback: Any | None = ...,
    ) -> bool: ...

class AsyncDatabase:
    """Asyncio database handle: thread-pool engine work; concurrent reads, exclusive writes."""

    @staticmethod
    def open(
        path: str, *, read_only: bool = ..., recovery: str | None = ...
    ) -> Awaitable[AsyncDatabase]: ...
    @staticmethod
    def open_in_memory() -> Awaitable[AsyncDatabase]: ...
    @staticmethod
    def open_snapshot_bytes(data: bytes) -> Awaitable[AsyncDatabase]: ...
    @staticmethod
    def open_snapshot(path: str) -> Awaitable[AsyncDatabase]: ...
    @staticmethod
    def restore_snapshot(snapshot_path: str, dest_path: str) -> Awaitable[None]: ...
    def path(self) -> Awaitable[str]: ...
    def register_collection(
        self,
        name: str,
        fields_json: str,
        primary_field: str,
        indexes_json: str | None = ...,
    ) -> Awaitable[tuple[int, int]]: ...
    def collection_names(self) -> Awaitable[list[str]]: ...
    def collection(self, name: str) -> AsyncCollection: ...
    def insert(self, collection_name: str, row: dict[str, Any]) -> Awaitable[None]: ...
    def delete(self, collection_name: str, pk: Any) -> Awaitable[None]: ...
    def get(
        self, collection_name: str, pk: Any
    ) -> Awaitable[dict[str, Any] | None]: ...
    def register_schema_version(
        self,
        collection_name: str,
        fields_json: str,
        indexes_json: str | None = ...,
        *,
        force: bool = ...,
    ) -> Awaitable[int]: ...
    def plan_schema_version(
        self,
        collection_name: str,
        fields_json: str,
        indexes_json: str | None = ...,
    ) -> Awaitable[dict[str, Any]]: ...
    def backfill_top_level_field(
        self,
        collection_name: str,
        field: str,
        value: Any,
    ) -> Awaitable[None]: ...
    def backfill_field_at_path(
        self,
        collection_name: str,
        path: list[str],
        value: Any,
    ) -> Awaitable[None]: ...
    def rebuild_indexes(self, collection_name: str) -> Awaitable[None]: ...
    def compact_to(self, dest_path: str) -> Awaitable[None]: ...
    def compact(self) -> Awaitable[None]: ...
    def snapshot_bytes(self) -> Awaitable[bytes]: ...
    def export_snapshot(self, dest_path: str) -> Awaitable[None]: ...
    def transaction(self) -> AsyncTransaction: ...

class AsyncCollection:
    def where(self, path: str | tuple[str, ...], value: Any) -> AsyncQuery: ...
    def gte_where(self, path: str | tuple[str, ...], value: Any) -> AsyncQuery: ...
    def all(
        self,
        *,
        fields: list[str | tuple[str, ...]]
        | tuple[str | tuple[str, ...], ...]
        | str
        | tuple[str, ...]
        | None = ...,
    ) -> Awaitable[list[dict[str, Any]]]: ...

class AsyncQuery:
    def and_where(self, path: str | tuple[str, ...], value: Any) -> AsyncQuery: ...
    def lt_where(self, path: str | tuple[str, ...], value: Any) -> AsyncQuery: ...
    def lte_where(self, path: str | tuple[str, ...], value: Any) -> AsyncQuery: ...
    def gt_where(self, path: str | tuple[str, ...], value: Any) -> AsyncQuery: ...
    def gte_where(self, path: str | tuple[str, ...], value: Any) -> AsyncQuery: ...
    def or_where(self, other: AsyncQuery) -> AsyncQuery: ...
    def order_by(
        self, path: str | tuple[str, ...], *, desc: bool = ...
    ) -> AsyncQuery: ...
    def limit(self, n: int) -> AsyncQuery: ...
    def explain(self) -> Awaitable[str]: ...
    def all(
        self,
        *,
        fields: list[str | tuple[str, ...]]
        | tuple[str | tuple[str, ...], ...]
        | str
        | tuple[str, ...]
        | None = ...,
    ) -> Awaitable[list[dict[str, Any]]]: ...

class Transaction(ContextManager[None]):
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None = ...,
        exc_value: BaseException | None = ...,
        traceback: Any | None = ...,
    ) -> bool: ...

class Database:
    """Sync database handle: concurrent reads (shared lock), exclusive writes."""

    @staticmethod
    def open(
        path: str, *, read_only: bool = ..., recovery: str | None = ...
    ) -> Database: ...
    @staticmethod
    def open_in_memory() -> Database: ...
    @staticmethod
    def open_snapshot_bytes(data: bytes) -> Database: ...
    @staticmethod
    def open_snapshot(path: str) -> Database: ...
    @staticmethod
    def restore_snapshot(snapshot_path: str, dest_path: str) -> None: ...
    def path(self) -> str: ...
    @overload
    def register_collection(
        self,
        name: str,
        fields_json: str,
        primary_field: str,
        indexes_json: None = ...,
    ) -> tuple[int, int]: ...
    @overload
    def register_collection(
        self,
        name: str,
        fields_json: str,
        primary_field: str,
        indexes_json: str,
    ) -> tuple[int, int]: ...
    def collection_names(self) -> list[str]: ...
    def collection(self, name: str) -> Collection: ...
    def insert(self, collection_name: str, row: dict[str, Any]) -> None: ...
    def delete(self, collection_name: str, pk: Any) -> None: ...
    def get(self, collection_name: str, pk: Any) -> dict[str, Any] | None: ...
    def register_schema_version(
        self,
        collection_name: str,
        fields_json: str,
        indexes_json: str | None = ...,
        *,
        force: bool = ...,
    ) -> int: ...
    def plan_schema_version(
        self,
        collection_name: str,
        fields_json: str,
        indexes_json: str | None = ...,
    ) -> dict[str, Any]: ...
    def backfill_top_level_field(
        self,
        collection_name: str,
        field: str,
        value: Any,
    ) -> None: ...
    def backfill_field_at_path(
        self,
        collection_name: str,
        path: list[str],
        value: Any,
    ) -> None: ...
    def rebuild_indexes(self, collection_name: str) -> None: ...
    def compact_to(self, dest_path: str) -> None: ...
    def compact(self) -> None: ...
    def snapshot_bytes(self) -> bytes: ...
    def export_snapshot(self, dest_path: str) -> None: ...
    def transaction(self) -> Transaction: ...

class Collection:
    def where(self, path: str | tuple[str, ...], value: Any) -> Query: ...
    def gte_where(self, path: str | tuple[str, ...], value: Any) -> Query: ...
    def all(
        self,
        *,
        fields: list[str | tuple[str, ...]]
        | tuple[str | tuple[str, ...], ...]
        | str
        | tuple[str, ...]
        | None = ...,
    ) -> list[dict[str, Any]]: ...

class Query:
    def and_where(self, path: str | tuple[str, ...], value: Any) -> Query: ...
    def lt_where(self, path: str | tuple[str, ...], value: Any) -> Query: ...
    def lte_where(self, path: str | tuple[str, ...], value: Any) -> Query: ...
    def gt_where(self, path: str | tuple[str, ...], value: Any) -> Query: ...
    def gte_where(self, path: str | tuple[str, ...], value: Any) -> Query: ...
    def or_where(self, other: Query) -> Query: ...
    def order_by(self, path: str | tuple[str, ...], *, desc: bool = ...) -> Query: ...
    def limit(self, n: int) -> Query: ...
    def explain(self) -> str: ...
    def all(
        self,
        *,
        fields: list[str | tuple[str, ...]]
        | tuple[str | tuple[str, ...], ...]
        | str
        | tuple[str, ...]
        | None = ...,
    ) -> list[dict[str, Any]]: ...

class _DbApiCursor(Protocol):
    description: tuple[tuple[Any, Any, Any, Any, Any, Any, Any], ...] | None
    def execute(self, sql: str, params: Sequence[Any] | None = ...) -> None: ...
    def fetchone(self) -> tuple[Any, ...] | None: ...
    def fetchmany(self, size: int = ...) -> list[tuple[Any, ...]]: ...
    def fetchall(self) -> list[tuple[Any, ...]]: ...
    def close(self) -> None: ...

class _DbApiConnection(Protocol):
    def cursor(self) -> _DbApiCursor: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...

class _DbApiModule(Protocol):
    def connect(
        self, path: str, *, strict_read_only: bool = ...
    ) -> _DbApiConnection: ...

dbapi: _DbApiModule

class FieldRef:
    path: list[str]

class ModelCollection:
    name: str
    def insert(self, obj: Any) -> None: ...
    def get(self, pk: Any) -> Any | None: ...
    def delete(self, pk_or_obj: Any) -> None: ...
    def update(self, pk: Any, patch: Any) -> None: ...
    def where(
        self, path: str | tuple[str, ...] | FieldRef, value: Any
    ) -> ModelQuery: ...
    def all(
        self,
        *,
        fields: list[str | tuple[str, ...] | FieldRef]
        | tuple[str | tuple[str, ...] | FieldRef, ...]
        | str
        | tuple[str, ...]
        | FieldRef
        | None = ...,
    ) -> list[Any]: ...

class ModelQuery:
    def select(
        self,
        fields: list[str | tuple[str, ...] | FieldRef]
        | tuple[str | tuple[str, ...] | FieldRef, ...]
        | str
        | tuple[str, ...]
        | FieldRef,
    ) -> ModelQuery: ...
    def and_where(
        self, path: str | tuple[str, ...] | FieldRef, value: Any
    ) -> ModelQuery: ...
    def limit(self, n: int) -> ModelQuery: ...
    def explain(self) -> str: ...
    def all(
        self,
        *,
        fields: list[str | tuple[str, ...] | FieldRef]
        | tuple[str | tuple[str, ...] | FieldRef, ...]
        | str
        | tuple[str, ...]
        | FieldRef
        | None = ...,
    ) -> list[Any]: ...

class AsyncModelCollection:
    name: str
    def insert(self, obj: Any) -> Awaitable[None]: ...
    def get(self, pk: Any) -> Awaitable[Any | None]: ...
    def delete(self, pk_or_obj: Any) -> Awaitable[None]: ...
    def update(self, pk: Any, patch: Any) -> Awaitable[None]: ...
    def where(
        self, path: str | tuple[str, ...] | FieldRef, value: Any
    ) -> AsyncModelQuery: ...
    def all(
        self,
        *,
        fields: list[str | tuple[str, ...] | FieldRef]
        | tuple[str | tuple[str, ...] | FieldRef, ...]
        | str
        | tuple[str, ...]
        | FieldRef
        | None = ...,
    ) -> Awaitable[list[Any]]: ...

class AsyncModelQuery:
    def select(
        self,
        fields: list[str | tuple[str, ...] | FieldRef]
        | tuple[str | tuple[str, ...] | FieldRef, ...]
        | str
        | tuple[str, ...]
        | FieldRef,
    ) -> AsyncModelQuery: ...
    def and_where(
        self, path: str | tuple[str, ...] | FieldRef, value: Any
    ) -> AsyncModelQuery: ...
    def limit(self, n: int) -> AsyncModelQuery: ...
    def explain(self) -> Awaitable[str]: ...
    def all(
        self,
        *,
        fields: list[str | tuple[str, ...] | FieldRef]
        | tuple[str | tuple[str, ...] | FieldRef, ...]
        | str
        | tuple[str, ...]
        | FieldRef
        | None = ...,
    ) -> Awaitable[list[Any]]: ...

class _ModelsModule(Protocol):
    def collection(self, db: Database, model_cls: type[Any]) -> ModelCollection: ...
    def async_collection(
        self, db: AsyncDatabase, model_cls: type[Any]
    ) -> AsyncModelCollection: ...
    def plan(self, db: Database, model_cls: type[Any]) -> Any: ...
    def async_plan(self, db: AsyncDatabase, model_cls: type[Any]) -> Awaitable[Any]: ...
    def apply(
        self, db: Database, model_cls: type[Any], *, force: bool = ...
    ) -> int: ...
    def async_apply(
        self, db: AsyncDatabase, model_cls: type[Any], *, force: bool = ...
    ) -> Awaitable[int]: ...
    def index(self, field: str, name: str | None = ...) -> Any: ...
    def unique(self, field: str, name: str | None = ...) -> Any: ...
    def constrained(self, **kwargs: Any) -> Any: ...

models: _ModelsModule
