[workspace]
members = [
    "crates/modelvault-core",
    "crates/modelvault-derive",
    "crates/modelvault",
    "crates/modelvault-cli",
    "python/modelvault",
    "fuzz",
]
resolver = "2"

[workspace.dependencies]
modelvault = { path = "crates/modelvault", version = "0.15.2" }
modelvault-core = { path = "crates/modelvault-core", version = "0.15.2" }
modelvault-derive = { path = "crates/modelvault-derive", version = "0.15.2" }

[workspace.package]
version = "0.15.2"
edition = "2021"
license = "MIT"
repository = "https://github.com/eddiethedean/modelvault"

[workspace.lints.rust]
unsafe_code = "forbid"
