from __future__ import annotations

from typing import Any, ContextManager, overload, Protocol, Sequence

__version__: str
__doc__: str

class Transaction(ContextManager[None]):
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None = ...,
        exc_value: BaseException | None = ...,
        traceback: Any | None = ...,
    ) -> bool: ...

class Database:
    @staticmethod
    def open(path: str) -> Database: ...
    @staticmethod
    def open_in_memory() -> Database: ...
    @staticmethod
    def open_snapshot_bytes(data: bytes) -> Database: ...
    def path(self) -> str: ...
    @overload
    def register_collection(
        self,
        name: str,
        fields_json: str,
        primary_field: str,
        indexes_json: None = ...,
    ) -> tuple[int, int]: ...
    @overload
    def register_collection(
        self,
        name: str,
        fields_json: str,
        primary_field: str,
        indexes_json: str,
    ) -> tuple[int, int]: ...
    def collection_names(self) -> list[str]: ...
    def collection(self, name: str) -> Collection: ...
    def insert(self, collection_name: str, row: dict[str, Any]) -> None: ...
    def delete(self, collection_name: str, pk: Any) -> None: ...
    def get(self, collection_name: str, pk: Any) -> dict[str, Any] | None: ...
    def register_schema_version(
        self,
        collection_name: str,
        fields_json: str,
        indexes_json: str | None = ...,
        *,
        force: bool = ...,
    ) -> int: ...
    def plan_schema_version(
        self,
        collection_name: str,
        fields_json: str,
        indexes_json: str | None = ...,
    ) -> dict[str, Any]: ...
    def backfill_top_level_field(
        self,
        collection_name: str,
        field: str,
        value: Any,
    ) -> None: ...
    def rebuild_indexes(self, collection_name: str) -> None: ...
    def compact_to(self, dest_path: str) -> None: ...
    def compact(self) -> None: ...
    def snapshot_bytes(self) -> bytes: ...
    def transaction(self) -> Transaction: ...

class Collection:
    def where(self, path: str | tuple[str, ...], value: Any) -> Query: ...
    def all(
        self,
        *,
        fields: list[str | tuple[str, ...]]
        | tuple[str | tuple[str, ...], ...]
        | str
        | tuple[str, ...]
        | None = ...,
    ) -> list[dict[str, Any]]: ...

class Query:
    def and_where(self, path: str | tuple[str, ...], value: Any) -> Query: ...
    def limit(self, n: int) -> Query: ...
    def explain(self) -> str: ...
    def all(
        self,
        *,
        fields: list[str | tuple[str, ...]]
        | tuple[str | tuple[str, ...], ...]
        | str
        | tuple[str, ...]
        | None = ...,
    ) -> list[dict[str, Any]]: ...

class _DbApiCursor(Protocol):
    description: tuple[tuple[Any, Any, Any, Any, Any, Any, Any], ...] | None
    def execute(self, sql: str, params: Sequence[Any] | None = ...) -> None: ...
    def fetchone(self) -> tuple[Any, ...] | None: ...
    def fetchmany(self, size: int = ...) -> list[tuple[Any, ...]]: ...
    def fetchall(self) -> list[tuple[Any, ...]]: ...
    def close(self) -> None: ...

class _DbApiConnection(Protocol):
    def cursor(self) -> _DbApiCursor: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...

class _DbApiModule(Protocol):
    def connect(self, path: str) -> _DbApiConnection: ...

dbapi: _DbApiModule
