from collections.abc import Mapping

__doc__: str
__version__: str

class Collection:
    def where(self, path: str | tuple[str, ...], value: object) -> Query: ...
    def all(
        self,
        fields: list[str | tuple[str, ...]]
        | tuple[str | tuple[str, ...], ...]
        | str
        | None = None,
    ) -> list[dict[str, object]]: ...

class Query:
    def limit(self, n: int) -> Query: ...
    def and_where(self, path: str | tuple[str, ...], value: object) -> Query: ...
    def explain(self) -> str: ...
    def all(
        self,
        fields: list[str | tuple[str, ...]]
        | tuple[str | tuple[str, ...], ...]
        | str
        | None = None,
    ) -> list[dict[str, object]]: ...

class Database:
    @staticmethod
    def open(path: str) -> Database: ...
    @staticmethod
    def open_in_memory() -> Database: ...
    @staticmethod
    def open_snapshot_bytes(data: bytes) -> Database: ...
    def path(self) -> str: ...
    def register_collection(
        self,
        name: str,
        fields_json: str,
        primary_field: str,
        indexes_json: str | None = None,
    ) -> tuple[int, int]: ...
    def collection_names(self) -> list[str]: ...
    def collection(self, name: str) -> Collection: ...
    def insert(self, collection_name: str, row: Mapping[str, object]) -> None: ...
    def get(self, collection_name: str, pk: object) -> dict[str, object] | None: ...
    def snapshot_bytes(self) -> bytes: ...
