__doc__: str
__version__: str

class Database:
    @staticmethod
    def open(path: str) -> Database: ...
    def path(self) -> str: ...
    def register_collection(self, name: str, fields_json: str) -> tuple[int, int]: ...
    def collection_names(self) -> list[str]: ...
