from collections.abc import Mapping

__doc__: str
__version__: str

class Database:
    @staticmethod
    def open(path: str) -> Database: ...
    @staticmethod
    def open_in_memory() -> Database: ...
    @staticmethod
    def open_snapshot_bytes(data: bytes) -> Database: ...
    def path(self) -> str: ...
    def register_collection(
        self, name: str, fields_json: str, primary_field: str
    ) -> tuple[int, int]: ...
    def collection_names(self) -> list[str]: ...
    def insert(self, collection_name: str, row: Mapping[str, object]) -> None: ...
    def get(self, collection_name: str, pk: object) -> dict[str, object] | None: ...
    def snapshot_bytes(self) -> bytes: ...
